FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV DISPLAY=:99

COPY requirements/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
