FROM lksmler/kiwi-base:latest AS base


WORKDIR /admin

COPY ./src/admin ./src/admin
COPY ./src/clients ./src/clients
COPY ./src/settings.py ./src/settings.py
COPY ./src/.env ./src/.env 


CMD ["uvicorn", "src.admin.app:app", "--host", "0.0.0.0", "--port", "9000", "--proxy-headers"]