FROM lksmler/kiwi-base:latest AS base


WORKDIR /widget

COPY ./src/widget ./src/widget
COPY ./src/settings.py ./src/settings.py
COPY ./src/.env ./src/.env 
COPY ./src/clients ./src/clients 

CMD ["uvicorn", "src.widget.frontend.app:app", "--host", "0.0.0.0", "--port", "9090", "--proxy-headers"]